<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="camera_x" value="0.01"/>
    <xacro:property name="camera_y" value="0.08"/>
    <xacro:property name="camera_z" value="0.01"/>
    <xacro:property name="camera_joint_x" value="${car_length/2 - 0.01}"/>
    <xacro:property name="camera_joint_y" value="0"/>
    <xacro:property name="camera_joint_z" value="${car_height/2 + camera_z/2}"/>
    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_x} ${camera_y} ${camera_z}"/>
            </geometry>
        </visual>
    </link>
    <joint name="camera2base_link" type="fixed">
        <parent link="base_link"/>
        <child link="camera"/>
        <origin xyz="${camera_joint_x} ${camera_joint_y} ${camera_joint_z}"/>
    </joint>
</robot>